// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXmwCvMI2jiCtInoANz6DAVgJktZEywkI',
    appId: '1:1001630017165:web:7479a3658e0100699864c4',
    messagingSenderId: '1001630017165',
    projectId: 'fir-715e1',
    authDomain: 'fir-715e1.firebaseapp.com',
    storageBucket: 'fir-715e1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7fw77_41wQd4HFvfgf5Y_3zbsTSG5crA',
    appId: '1:1001630017165:android:926eb53af2191a6e9864c4',
    messagingSenderId: '1001630017165',
    projectId: 'fir-715e1',
    storageBucket: 'fir-715e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmBqHxtihf6iXoe36GRQDYM_5uPPwN_m8',
    appId: '1:1001630017165:ios:3b309c33c8555a899864c4',
    messagingSenderId: '1001630017165',
    projectId: 'fir-715e1',
    storageBucket: 'fir-715e1.firebasestorage.app',
    iosBundleId: 'com.example.amazonClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmBqHxtihf6iXoe36GRQDYM_5uPPwN_m8',
    appId: '1:1001630017165:ios:3b309c33c8555a899864c4',
    messagingSenderId: '1001630017165',
    projectId: 'fir-715e1',
    storageBucket: 'fir-715e1.firebasestorage.app',
    iosBundleId: 'com.example.amazonClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXmwCvMI2jiCtInoANz6DAVgJktZEywkI',
    appId: '1:1001630017165:web:dae7a1866be0a5739864c4',
    messagingSenderId: '1001630017165',
    projectId: 'fir-715e1',
    authDomain: 'fir-715e1.firebaseapp.com',
    storageBucket: 'fir-715e1.firebasestorage.app',
  );
}
